services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./mongo-data:/data/db
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/cargo-db

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
